# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c350a6b2e69d1354ab4e68e5ab5d802361fc33775205ade2e585189d3ee8e1ff39facbb4358085996a2dc7e9708b549f622867665e3e74c8e6e495390ef34371

test:
  secret_key_base: b289bc2fbc3c28a341304379630c1554f95cbfc612bb6dd59edadc319fca1a4bc39fa506cd24ac338d102c3ed4cfd668fd43690390d0c3f30f1b64342a524a08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
